---
services:
  your_spotify:
    image: lscr.io/linuxserver/your_spotify:latest
    hostname: your-spotify
    container_name: your_spotify
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - APP_URL=${TS_URL}
      - SPOTIFY_PUBLIC=${SPOTIFY_PUBLIC}
      - SPOTIFY_SECRET=${SPOTIFY_SECRET}
      - CORS=http://localhost:80,https://localhost:443
      - MONGO_ENDPOINT=mongodb://mongo:27017/your_spotify
#    ports:
#      - 80:80
#      - 443:443
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:80"]
      interval: 1m # How often to perform the check
      timeout: 10s # Time to wait for the check to succeed
      retries: 3 # Number of retries before marking as unhealthy
      start_period: 10s # Time to wait before starting health checks
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_started
      tailscale-your_spotify:
        condition: service_healthy
#    network_mode: service:tailscale-your_spotify

  mongo:
    container_name: mongo
    image: mongo:4.4
    hostname: mongo
    restart: always
    volumes:
      - ${PWD}/your_spotify_db:/data/db

  tailscale-your_spotify:
    image: tailscale/tailscale:latest
    container_name: tailscale-your_spotify
    environment:
      - TS_AUTHKEY=${TS_KEY_YOUR_SPOTIFY}
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_SERVE_CONFIG=/config/your_spotify.json
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_HOSTNAME=your-spotify
      - TS_USERSPACE=false
      - TS_ENABLE_HEALTH_CHECK=true              # Enable healthcheck endpoint: "/healthz"
      - TS_LOCAL_ADDR_PORT=127.0.0.1:41234       # The <addr>:<port> for the healthz endpoint
    volumes:
      - ${PWD}/tailscale-your_spotify/state:/var/lib/tailscale
      - ${PWD}/tailscale-your_spotify/config:/config
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    # networks:
    #  - ...
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:41234/healthz"] # Check Tailscale has a Tailnet IP and is operational
      interval: 1m # How often to perform the check
      timeout: 10s # Time to wait for the check to succeed
      retries: 3 # Number of retries before marking as unhealthy
      start_period: 10s # Time to wait before starting health checks
    restart: unless-stopped
