services:

  grafana:
    image: grafana/grafana-enterprise:latest
    container_name: grafana
    # ports
    # - 3000:3000
    # user: "$(id -u)"
    network_mode: service:tailscale-grafana
    depends_on:
      tailscale-grafana:
        condition: service_healthy
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      # to install plugins for grafana
      - GF_PLUGINS_PREINSTALL=grafana-clock-panel, grafana-simple-json-datasource, grafana-github-datasource
    healthcheck:
      test: ["CMD", "pgrep", "-f", "grafana"] # Check if ${SERVICE} process is running
      interval: 1m # How often to perform the check
      timeout: 10s # Time to wait for the check to succeed
      retries: 3 # Number of retries before marking as unhealthy
      start_period: 10s # Time to wait before starting health checks 
    restart: unless-stopped

  tailscale-grafana:
    image: tailscale/tailscale:latest
    container_name: tailscale-grafana
    environment:
      - TS_AUTHKEY=${TS_KEY_GRAFANA}
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_SERVE_CONFIG=/config/grafana.json
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_HOSTNAME=grafana
      - TS_USERSPACE=false
      - TS_ENABLE_HEALTH_CHECK=true              # Enable healthcheck endpoint: "/healthz"
      - TS_LOCAL_ADDR_PORT=127.0.0.1:41234       # The <addr>:<port> for the healthz endpoint
    volumes:
      - ${PWD}/tailscale-grafana/state:/var/lib/tailscale
      - ${PWD}/tailscale-grafana/config:/config
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    # networks:
    #  - ...
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:41234/healthz"] # Check Tailscale has a Tailnet IP and is operational
      interval: 1m # How often to perform the check
      timeout: 10s # Time to wait for the check to succeed
      retries: 3 # Number of retries before marking as unhealthy
      start_period: 10s # Time to wait before starting health checks
    restart: unless-stopped

volumes:
  grafana-data:
