services:
  uptime-kuma:
    image: louislam/uptime-kuma:2
    container_name: uptime-kuma
    restart: unless-stopped
#    environment:
#      - UPTIME_KUMA_WS_ORIGIN_CHECK=bypass
#      - UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN=true
#      - NODE_OPTIONS=--insecure-http-parser
    volumes:
      - ./data:/app/data
#    ports:
#      # <Host Port>:<Container Port>
#      - "3001:3001"
    network_mode: service:tailscale-uptime-kuma
    depends_on:
      tailscale-uptime-kuma:
        condition: service_healthy

  tailscale-uptime-kuma:
    image: tailscale/tailscale:latest
    container_name: tailscale-uptime-kuma
    environment:
      - TS_AUTHKEY=${TS_KEY_UPTIME_KUMA}
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_SERVE_CONFIG=/config/uptime-kuma.json
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_HOSTNAME=uptime-kuma
      - TS_USERSPACE=false
      - TS_ENABLE_HEALTH_CHECK=true              # Enable healthcheck endpoint: "/healthz"
      - TS_LOCAL_ADDR_PORT=127.0.0.1:41234       # The <addr>:<port> for the healthz endpoint
    volumes:
      - ${PWD}/tailscale-uptime-kuma/state:/var/lib/tailscale
      - ${PWD}/tailscale-uptime-kuma/config:/config
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    # networks:
    #  - ...
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:41234/healthz"] # Check Tailscale has a Tailnet IP and is operational
      interval: 1m # How often to perform the check
      timeout: 10s # Time to wait for the check to succeed
      retries: 3 # Number of retries before marking as unhealthy
      start_period: 10s # Time to wait before starting health checks
    restart: unless-stopped
